# Generated by Django 4.1 on 2023-10-23 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('avatar', models.TextField(blank=True, max_length=500)),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Amministratore Scuola'), ('teacher', 'Insegnante'), ('student', 'Studente')], default='student', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassroomSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(choices=[('pdf', 'PDF'), ('mp3', 'MP3'), ('wma', 'WMA'), ('mp4', 'MP4'), ('jpg', 'JPG'), ('png', 'PNG')], max_length=100)),
                ('macro_type', models.CharField(choices=[('vid', 'VIDEO'), ('img', 'IMMAGINE'), ('doc', 'DOCUMENTO'), ('aud', 'AUDIO')], max_length=100)),
                ('megabyte_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nuova Scuola', max_length=100)),
                ('custom_id', models.CharField(default=users.models.generate_unique_code, max_length=10, unique=True)),
                ('info', models.TextField(blank=True, max_length=500, verbose_name='info')),
                ('is_active', models.BooleanField(default=True)),
                ('theme', models.CharField(default='Default', max_length=100)),
                ('modulo_ingresso', models.BooleanField(default=False)),
                ('modulo_comunicazione_multipla', models.BooleanField(default=False)),
                ('modulo_personalizzato_apprendimento', models.BooleanField(default=False)),
                ('modulo_eventi', models.BooleanField(default=False)),
                ('modulo_segreteria', models.BooleanField(default=False)),
                ('modulo_spazio_docenti', models.BooleanField(default=False)),
                ('modulo_classi_innovative', models.BooleanField(default=False)),
                ('planimetry_image', models.FileField(upload_to=users.models.school_directory_path)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='SiteLogins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Site Logins',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=users.models.user_directory_path)),
                ('path', models.CharField(max_length=100)),
                ('byte_space', models.FloatField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mediatype')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lab', 'Laboratorio'), ('class', 'Aula')], default='class', max_length=100)),
                ('name', models.CharField(default='Standard', max_length=100)),
                ('room_number', models.PositiveIntegerField(default=1)),
                ('media_files', models.ManyToManyField(blank=True, to='users.mediafile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='users.school')),
                ('skin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.classroomskin')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.school'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
