# Generated by Django 4.1 on 2023-10-23 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_school_planimetry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
