# Generated by Django 4.1 on 2023-10-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mediafile_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('news', 'News'), ('doc', 'Documento'), ('meet', 'Appuntamento')], max_length=100)),
                ('text', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=100)),
                ('meet_link', models.CharField(blank=True, max_length=100)),
                ('media_file', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.mediafile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
        ),
    ]
