# Generated by Django 4.1 on 2023-10-26 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_notices_notice_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='media_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mediafile'),
        ),
    ]
