# Generated by Django 4.1 on 2023-11-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='last_modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='area_id',
            field=models.CharField(choices=[('1', 'Sezione 1'), ('2', 'Sezione 2'), ('3', 'Sezione 3')], max_length=100),
        ),
    ]
