# Generated by Django 4.1 on 2023-11-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_faqsection_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='school',
        ),
    ]
