# Generated by Django 4.1 on 2023-11-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_notice_date_notice_modify_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='last_modify',
            new_name='last_modify_date',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='modify_date',
            new_name='last_modify_date',
        ),
    ]
