# Generated by Django 4.1 on 2023-11-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_last_modify_faq_last_modify_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='listening_desk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
