# Generated by Django 4.1 on 2023-11-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_school_listening_desk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='listening_desk',
            field=models.CharField(blank=True, default='Non impostato', max_length=100, null=True),
        ),
    ]
