# Generated by Django 4.1 on 2023-10-23 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.CharField(choices=[('access', 'Accessi'), ('actions', 'Azioni')], default='actions', max_length=100)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('failed', 'Fallito'), ('success', 'Successo')], default='failed', max_length=100)),
                ('imported_actions', models.IntegerField(default=0)),
                ('exhibitions_updated', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Import',
                'verbose_name_plural': 'Imports',
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('info', models.TextField(blank=True, max_length=500, verbose_name='info')),
            ],
            options={
                'verbose_name': 'Stand',
                'verbose_name_plural': 'Stands',
            },
        ),
        migrations.CreateModel(
            name='Pavilion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('info', models.TextField(blank=True, max_length=500, verbose_name='info')),
                ('stands', models.ManyToManyField(blank=True, to='advepa.stand')),
            ],
            options={
                'verbose_name': 'Pavilion',
                'verbose_name_plural': 'Pavilions',
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('info', models.TextField(blank=True, max_length=500, verbose_name='info')),
                ('pavilions', models.ManyToManyField(blank=True, to='advepa.pavilion')),
            ],
            options={
                'verbose_name': 'Exhibition',
                'verbose_name_plural': 'Exhibitions',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('date_string', models.CharField(default='', max_length=150)),
                ('user', models.CharField(max_length=150)),
                ('main_action', models.CharField(max_length=150)),
                ('action_detail', models.CharField(max_length=150)),
                ('platform', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('province', models.CharField(max_length=150)),
                ('municipality', models.CharField(max_length=150)),
                ('geo_string', models.CharField(default='', max_length=150)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advepa.exhibition')),
                ('pavilion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advepa.pavilion')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advepa.stand')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
    ]
