# Generated by Django 4.1 on 2023-11-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advepa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='exhibition',
        ),
        migrations.RemoveField(
            model_name='action',
            name='pavilion',
        ),
        migrations.RemoveField(
            model_name='action',
            name='stand',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='pavilions',
        ),
        migrations.DeleteModel(
            name='GraphInteraction',
        ),
        migrations.DeleteModel(
            name='Import',
        ),
        migrations.RemoveField(
            model_name='pavilion',
            name='stands',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Exhibition',
        ),
        migrations.DeleteModel(
            name='Pavilion',
        ),
        migrations.DeleteModel(
            name='Stand',
        ),
    ]
